server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

  application:
    name: INVENTORY-SERVICE

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order
      product-group-id: product
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
